import {
  warmMatrix,
  coolMatrix,
  magentaMatrix,
  greenMatrix,
  fadedMatrix,
  bwMatrix,
  bleachMatrix,
} from './matrixUtils.js';

export const FUJI_PACK = {
  id: 'fuji',
  name: 'Fuji',
  presets: [
    { id: 'fuji-velvia-50', name: 'Velvia 50', desc: 'Saturated landscape', swatch: '#b53870',
      contrast: 0.18, saturation: 0.35, vibrance: 0.2, colorMatrix: magentaMatrix(0.3) },
    { id: 'fuji-velvia-100', name: 'Velvia 100', desc: 'Vivid color punch', swatch: '#a83a76',
      contrast: 0.15, saturation: 0.3, vibrance: 0.15, colorMatrix: magentaMatrix(0.22) },
    { id: 'fuji-provia-100f', name: 'Provia 100F', desc: 'Balanced pro slide', swatch: '#4f9e74',
      contrast: 0.12, saturation: 0.15, colorMatrix: greenMatrix(0.18) },
    { id: 'fuji-astia-100f', name: 'Astia 100F', desc: 'Soft portrait slide', swatch: '#d6a6a0',
      brightness: 0.04, contrast: 0.06, saturation: 0.08, colorMatrix: warmMatrix(0.08, 0.02) },
    { id: 'fuji-pro-400h', name: 'Pro 400H', desc: 'Pastel wedding film', swatch: '#bcd1c6',
      brightness: 0.05, contrast: 0.04, saturation: -0.05, colorMatrix: greenMatrix(0.1) },
    { id: 'fuji-pro-160ns', name: 'Pro 160NS', desc: 'Neutral skin tone', swatch: '#dbb39a',
      brightness: 0.03, contrast: 0.06, saturation: 0.06, colorMatrix: warmMatrix(0.08, 0.02) },
    { id: 'fuji-pro-800z', name: 'Pro 800Z', desc: 'Warm fast portrait', swatch: '#c98f6c',
      brightness: 0.02, contrast: 0.1, saturation: 0.1, colorMatrix: warmMatrix(0.15, 0) },
    { id: 'fuji-superia-200', name: 'Superia 200', desc: 'Daily green-leaning', swatch: '#6db062',
      contrast: 0.1, saturation: 0.15, colorMatrix: greenMatrix(0.2) },
    { id: 'fuji-superia-400', name: 'Superia 400', desc: 'Versatile color', swatch: '#7ab27a',
      contrast: 0.1, saturation: 0.18, colorMatrix: greenMatrix(0.22) },
    { id: 'fuji-superia-xtra-800', name: 'Superia X-TRA 800', desc: 'Punchy fast film', swatch: '#5fa46a',
      contrast: 0.14, saturation: 0.22, colorMatrix: greenMatrix(0.24) },
    { id: 'fuji-c200', name: 'C200', desc: 'Budget consumer', swatch: '#7caf6f',
      contrast: 0.08, saturation: 0.15, colorMatrix: greenMatrix(0.18) },
    { id: 'fuji-natura-1600', name: 'Natura 1600', desc: 'Ultra-fast neutral', swatch: '#9aa0a8',
      contrast: 0.12, saturation: 0.05, colorMatrix: coolMatrix(0.08, 0) },
    { id: 'fuji-eterna-cinema', name: 'Eterna Cinema', desc: 'Muted cinematic', swatch: '#7d8b7a',
      contrast: -0.04, saturation: -0.2, colorMatrix: fadedMatrix(0.05, 0.25) },
    { id: 'fuji-classic-chrome', name: 'Classic Chrome', desc: 'Muted documentary', swatch: '#8d7a64',
      contrast: 0.05, saturation: -0.1, colorMatrix: fadedMatrix(0.02, 0.15) },
    { id: 'fuji-classic-negative', name: 'Classic Negative', desc: 'Vintage negative', swatch: '#a08456',
      contrast: 0.1, saturation: 0.05, colorMatrix: warmMatrix(0.1, 0) },
    { id: 'fuji-acros-100-bw', name: 'Acros 100 BW', desc: 'Smooth fine B&W', swatch: '#5c5c5c',
      contrast: 0.18, saturation: -1, colorMatrix: bwMatrix(0, 0, 0) },
    { id: 'fuji-neopan-1600-bw', name: 'Neopan 1600 BW', desc: 'Grainy fast B&W', swatch: '#3d3d3d',
      contrast: 0.28, saturation: -1, colorMatrix: bwMatrix(0, 0, 0) },
    { id: 'fuji-reala-skin', name: 'Reala Skin', desc: 'Skin-accurate', swatch: '#e3b59a',
      brightness: 0.04, contrast: 0.06, saturation: 0.08, colorMatrix: warmMatrix(0.1, 0.02) },
    { id: 'fuji-nostalgic-neg', name: 'Nostalgic Neg', desc: 'Amber memory', swatch: '#bc8a52',
      brightness: 0.03, contrast: 0.08, saturation: 0.05, colorMatrix: warmMatrix(0.2, 0.01) },
    { id: 'fuji-bleach-bypass', name: 'Bleach Bypass', desc: 'Gritty desaturated', swatch: '#888076',
      contrast: 0.2, saturation: -0.4, colorMatrix: bleachMatrix(0.5, 0.12) },
  ],
};
