import {
  warmMatrix,
  coolMatrix,
  magentaMatrix,
  greenMatrix,
  fadedMatrix,
  bwMatrix,
  tealOrangeMatrix,
} from './matrixUtils.js';

// Each preset returns settings layered on top of FILTER_DEFAULTS.
// Properties supported: brightness, contrast, saturation, hue, vibrance, gamma, colorMatrix, swatch, desc.

export const KODAK_PACK = {
  id: 'kodak',
  name: 'Kodak',
  presets: [
    { id: 'kodak-gold-200', name: 'Gold 200', desc: 'Warm, golden sun', swatch: '#e8b56a',
      brightness: 0.04, contrast: 0.08, saturation: 0.12, colorMatrix: warmMatrix(0.18, 0.02) },
    { id: 'kodak-portra-160', name: 'Portra 160', desc: 'Soft skin tones', swatch: '#e7c4a4',
      brightness: 0.03, contrast: 0.04, saturation: 0.05, colorMatrix: warmMatrix(0.1, 0.03) },
    { id: 'kodak-portra-400', name: 'Portra 400', desc: 'Creamy portraits', swatch: '#d9a98a',
      brightness: 0.05, contrast: 0.06, saturation: 0.08, colorMatrix: warmMatrix(0.13, 0.03) },
    { id: 'kodak-portra-800', name: 'Portra 800', desc: 'Low-light portrait', swatch: '#b88466',
      brightness: 0.02, contrast: 0.12, saturation: 0.1, colorMatrix: warmMatrix(0.16, 0.0) },
    { id: 'kodak-ektar-100', name: 'Ektar 100', desc: 'Vibrant landscape', swatch: '#d54b3a',
      contrast: 0.12, saturation: 0.28, vibrance: 0.2, colorMatrix: warmMatrix(0.08, 0.0) },
    { id: 'kodak-colorplus-200', name: 'ColorPlus 200', desc: 'Everyday warm', swatch: '#e0a766',
      brightness: 0.04, contrast: 0.06, saturation: 0.12, colorMatrix: warmMatrix(0.15, 0.02) },
    { id: 'kodak-ultramax-400', name: 'Ultramax 400', desc: 'Punchy snapshots', swatch: '#e58a3d',
      contrast: 0.1, saturation: 0.18, vibrance: 0.1, colorMatrix: warmMatrix(0.2, 0.02) },
    { id: 'kodak-pro-image-100', name: 'Pro Image 100', desc: 'Pro warm balance', swatch: '#dba27a',
      brightness: 0.03, contrast: 0.07, saturation: 0.1, colorMatrix: warmMatrix(0.14, 0.02) },
    { id: 'kodak-vision3-250d', name: 'Vision3 250D', desc: 'Daylight cine', swatch: '#c79a73',
      contrast: 0.1, saturation: 0.08, colorMatrix: warmMatrix(0.1, 0.0) },
    { id: 'kodak-vision3-500t', name: 'Vision3 500T', desc: 'Tungsten cine', swatch: '#8c9bbd',
      contrast: 0.12, saturation: 0.06, colorMatrix: coolMatrix(0.18, -0.02) },
    { id: 'kodak-trix-400-bw', name: 'Tri-X 400 BW', desc: 'Classic grain B&W', swatch: '#454545',
      contrast: 0.25, saturation: -1, colorMatrix: bwMatrix(0, 0, 0) },
    { id: 'kodak-tmax-100-bw', name: 'T-Max 100 BW', desc: 'Fine-grain B&W', swatch: '#5a5a5a',
      contrast: 0.18, saturation: -1, colorMatrix: bwMatrix(0, 0, 0) },
    { id: 'kodak-tmax-400-bw', name: 'T-Max 400 BW', desc: 'Versatile B&W', swatch: '#4f4f4f',
      contrast: 0.22, saturation: -1, colorMatrix: bwMatrix(0, 0, 0) },
    { id: 'kodak-bw400cn', name: 'BW400CN', desc: 'Soft chromogenic B&W', swatch: '#6b6258',
      contrast: 0.15, saturation: -1, colorMatrix: bwMatrix(0.03, 0.02, 0) },
    { id: 'kodak-aerochrome-ir', name: 'Aerochrome IR', desc: 'Surreal infrared', swatch: '#d24a7a',
      contrast: 0.15, saturation: 0.35, colorMatrix: magentaMatrix(0.4) },
    { id: 'kodak-elite-chrome-100', name: 'Elite Chrome 100', desc: 'Slide film snap', swatch: '#3f9fd8',
      contrast: 0.18, saturation: 0.22, colorMatrix: coolMatrix(0.1, 0) },
    { id: 'kodak-ektachrome-e100', name: 'Ektachrome E100', desc: 'Clean slide', swatch: '#62b1d4',
      contrast: 0.12, saturation: 0.15, colorMatrix: coolMatrix(0.08, 0) },
    { id: 'kodak-kodachrome-25', name: 'Kodachrome 25', desc: 'Rich, deep slides', swatch: '#a83b2c',
      contrast: 0.2, saturation: 0.25, colorMatrix: warmMatrix(0.18, -0.02) },
    { id: 'kodak-kodachrome-64', name: 'Kodachrome 64', desc: 'Iconic warm slide', swatch: '#c4583a',
      contrast: 0.18, saturation: 0.22, colorMatrix: warmMatrix(0.2, -0.01) },
    { id: 'kodak-kodachrome-200', name: 'Kodachrome 200', desc: 'Faster slide warmth', swatch: '#c97049',
      contrast: 0.15, saturation: 0.2, colorMatrix: warmMatrix(0.18, 0) },
    { id: 'kodak-disposable-yellow', name: 'Disposable Yellow', desc: 'Vintage point-and-shoot', swatch: '#e8c054',
      brightness: 0.05, contrast: 0.08, saturation: 0.05, colorMatrix: warmMatrix(0.22, 0.03) },
    { id: 'kodak-sunny-summer', name: 'Sunny Summer', desc: 'Bright outdoor glow', swatch: '#f4c87a',
      brightness: 0.08, contrast: 0.08, saturation: 0.18, vibrance: 0.1, colorMatrix: warmMatrix(0.15, 0.04) },
    { id: 'kodak-faded-memory', name: 'Faded Memory', desc: 'Lifted, washed out', swatch: '#d6c7b3',
      brightness: 0.04, contrast: -0.1, saturation: -0.15, colorMatrix: fadedMatrix(0.1, 0.3) },
    { id: 'kodak-cinematic-teal', name: 'Cinematic Teal', desc: 'Teal & orange cine', swatch: '#3a8c8c',
      contrast: 0.15, saturation: 0.05, colorMatrix: tealOrangeMatrix(0.25) },
    { id: 'kodak-cool-studio', name: 'Cool Studio', desc: 'Even, cool light', swatch: '#7aa9c4',
      contrast: 0.06, saturation: 0.0, colorMatrix: coolMatrix(0.15, 0.01) },
    { id: 'kodak-warm-studio', name: 'Warm Studio', desc: 'Even, warm light', swatch: '#d8a878',
      contrast: 0.06, saturation: 0.05, colorMatrix: warmMatrix(0.15, 0.02) },
    { id: 'kodak-polaroid-vibe', name: 'Polaroid Vibe', desc: 'Soft instant film', swatch: '#e0d2a8',
      brightness: 0.05, contrast: -0.06, saturation: -0.05, colorMatrix: fadedMatrix(0.08, 0.2) },
    { id: 'kodak-reversal-print', name: 'Reversal Print', desc: 'Slide-to-print look', swatch: '#c89058',
      contrast: 0.18, saturation: 0.18, colorMatrix: warmMatrix(0.12, -0.01) },
  ],
};
